spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tienda_db
    username: tienda_user
    password: tienda_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
